*Using np.empty*

In [ ]:
import numpy as np
a = np.empty([2, 2], dtype = int)
print ('Matrix a \n', a)
b = np.empty(2, dtype = int)
print ('Matrix b \n', b)

Matrix a 
 [[15  9]
 [ 6 12]]
Matrix b 
 [265180945866440260 144443560684213053]


*Using np.zeros*

In [ ]:
a = np.zeros([2, 2], dtype=int)
print('Matrix a:\n', a)
b = np.zeros(3, dtype=int)
print('Matrix b:\n', b)
c = np.zeros([3, 3])
print('Matrix c:\n', c)


Matrix a:
 [[0 0]
 [0 0]]
Matrix b:
 [0 0 0]
Matrix c:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


using np.add

In [ ]:
a = np.array([24, 26, 55, 45, 35])
b = np.array([26, 39, 49, 66, 88])
print(np.add(a, b))

[ 50  65 104 111 123]


using np.subtract

In [ ]:
print(np.subtract(a, b))

[ -2 -13   6 -21 -53]


using np.divide

In [ ]:
print(np.divide(a, b))

[0.92307692 0.66666667 1.12244898 0.68181818 0.39772727]


using np.multiply

In [ ]:
print(np.multiply(a, b))

[ 624 1014 2695 2970 3080]


Indexing

In [ ]:
a = np.arange(15, 2, -3)
print('Values are \n', a)

newArr = a[np.array([0, 2, 3, 1])]
print('Selected Indices are\n', newArr)

Values are 
 [15 12  9  6  3]
Selected Indices are
 [15  9  6 12]


Slicing

In [ ]:
a = np.arange(30)
print(a)
print('a[-6: 17: 1]', a[-20:28:2])
print(a[10:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
a[-6: 17: 1] [10 12 14 16 18 20 22 24 26]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


Using elipsis

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]]
            [[7, 8, 9], [10, 11, 12]])
print(b([..., 1]))

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_4350/732187684.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  b = np.array([[1, 2, 3], [4, 5, 6]]


TypeError: list indices must be integers or slices, not tuple